
/**
 * RDBMSAdapter
 *
 * A generic, promise-based SQL database adapter that wraps any database client
 * conforming to a unified interface. This adapter provides common query and
 * transaction functionality in a consistent async API.
 *
 * Works with drivers generated by the `createDbAdapterDriver(rawDb, type)` factory.
 *
 * ------------------------------------------
 * Expected driver interface:
 * {
 *   prepare: (sql: string) => Promise<{
 *     run: (binds?: any[]) => Promise<{ changes: number }>,
 *     all: (binds?: any[]) => Promise<any[]>
 *   }>,
 *   exec: (sql: string) => Promise<any>,
 *   close: () => Promise<void>
 * }
 * ------------------------------------------
 *
 * Supports:
 * - better-sqlite3
 * - mysql2
 * - pg
 * - (extensible to others via the driver factory)
 *
 * Example usage:
 *      const driver = createDbAdapterDriver(db, 'better-sqlite3');
 *      const myadb = new AsyncRDBMSAdapter(driver);
 *      const result = await myadb._runQuery('SELECT * FROM INVENTORY WHERE id = @id', { id: 4 });
 *      console.log(result);
 *      will log: [ { id: 4, barcode: '12345', name: 'Widget', quantity: 10, ... } ]
 */

const JsonFormatter = require('./formatter/json');
const BaseAdapter = require('./base/base-adapter');

class RDBMSAdapter extends BaseAdapter {
    #db;
    #formatter;
    #isClosed = false;

    constructor(driver, formatter = new JsonFormatter()) {
        super();
        this.#db = driver;
        this.#formatter = formatter;
    }

    setDbDriver(newDriver) {
        this.#db = newDriver;
        this.#isClosed = false;
        return this;
    }

    getDbType(){
        return this.#db.type;
    }

    setFormatter(newFormatter) {
        this.#formatter = newFormatter;
        return this;
    }

    async formatOutput(data) {
        return this.#formatter.format(data);
    }

    async query(queryStr, localBinds = {}) {
        const rawData = await super.query(queryStr, localBinds);
        return this.formatOutput(rawData);
    }

    async dml(dmlStr, localBinds = {}) {
        const changes = await super.dml(dmlStr, localBinds);
        return this.formatOutput( { changes });
    }

    async dmlReturning(dmlStr, localBinds = {}) {
        const changes = await super.dmlReturning(dmlStr, localBinds);
        return this.formatOutput( changes );
    }

    async close() {
        if (this.#isClosed) return;

        try {
            if (this.isTransactionActive?.()) {
                await this.rollbackTransaction();
            }
            await this.#db.close();
        } finally {
            this.#isClosed = true;
        }
    }

    /**
     * @protected
     * @internal
     * @override
     */
    // Runs SELECT or other queries returning rows
    async _runQuery(sql, binds) {
        this.#checkConnection();
        const stmt = await this.#db.prepare(sql);
        try {
            return await stmt.all(binds);
        } finally {
            try {
                if (stmt.close) {
                    await stmt.close();
                }
            } catch (error) {
                console.warn('Statement close error:', error.message);
            }
        }
    }

    /**
     * @protected
     * @internal
     * @override
     */
    // Runs INSERT, UPDATE, DELETE, etc.
    async _runDML(sql, binds) {
        this.#checkConnection();
        const stmt = await this.#db.prepare(sql);
        try {
            const result = await stmt.run(binds);
            return result.changes;
        } finally {
            try {
                if (stmt.close) {
                    await stmt.close();  
                }
            } catch (error) {
                console.warn('Statement close error:', error.message);
            }
        }
    }

    async _runDMLReturning(sql, binds) {
        this.#checkConnection();
        const stmt = await this.#db.prepare(sql);
        try {
            return await stmt.returningRun(binds);
        } finally {
            try {
                if (stmt.close) {
                    await stmt.close();
                }
            } catch (error) {
                console.warn('Statement close error:', error.message);
            }
        }
    }

    async _beginTransaction() {
        return this.#exec('BEGIN TRANSACTION');
    }

    async _commitTransaction() {
        return this.#exec('COMMIT');
    }

    async _rollbackTransaction() {
        return this.#exec('ROLLBACK');
    }

    async #exec(sql) {
        this.#checkConnection();
        return this.#db.exec(sql);
    }

    #checkConnection() {
        if (this.#isClosed) {
            throw new Error('Database connection closed');
        }
    }

    isOpen() {
        return !this.#isClosed;
    }
}

module.exports = RDBMSAdapter;